modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="aether_reborn"
version="1.0.0"
displayName="Aether Reborn"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="shane, MCreator"

[[dependencies.aether_reborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



