modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="aetherreborn"
version="1.0.0"
displayName="Aether Reborn"
credits="Gilded Games."
displayURL="https://officiallysp.sytes.net"
authors="Shane"
description='''
The Aether Mod Updated To Modern Minecraft
'''

[[dependencies.aetherreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



